@Library('srikanth-demo') _
pipeline {
    agent any
    stages {
        stage ('demo') {
            steps {
                script {
                welcome("shankar")
                login.access("shankar")
            }
            }
            
        }
    }
    
}
