def util;
pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                script{
                    util = load("${env.WORKSPACE}/scripts/build_util.groovy")
                    util.test1()
                }
            }
        }
    }
}
