Map modules = [:]
pipeline {
    agent any
    stages {
        stage('test') {
            steps {
                script{
                    modules.first = load "$WORKSPACE\modules\first.groovy"
                    modules.first.test1()
   
                }
            }
        }
    }
}
